"""Per-session plan artifact storage — Sprint 12 PR 12.4.

Each session that enters plan mode gets a stable Markdown file under
``${AETHER_HOME}/plans/<session_id[:8]>.md``.  The artifact is the
shared source of truth between:

- :class:`~aether.tools.builtins.exit_plan_mode.ExitPlanModeTool`,
  which writes the model's proposed plan BEFORE prompting for
  approval (so reject still leaves the plan visible for revision).
- The gateway ``plan.current`` RPC, which reads it for the TUI.
- The TUI's ``/plan`` and ``/plan open`` commands (PR 12.2).
- ``/clear`` / ``/resume`` lifecycle (PR 12.6).

Design constraints:

- Path is fully derived from ``session_id``; same id always maps to
  the same file (idempotent overwrite, not append).
- ``session_id`` is validated against path-traversal so an attacker
  who somehow controls it cannot escape the plans directory.
- ``read_plan`` on a missing file returns ``None``, never raises —
  ``plan.current`` and ``/plan`` rely on this to render a no-plan
  state cleanly.
- ``clear_plan`` is idempotent so ``/clear`` can call it unconditionally.

We deliberately do NOT introduce a separate config knob for the plans
directory.  Sticking with ``${AETHER_HOME}/plans`` matches the
``sessions`` / ``prefs`` / ``logs`` layout the rest of Aether already
uses (see :mod:`aether.cli.prefs` and :mod:`aether.cli.sessions`).
"""

from __future__ import annotations

import logging
import os
import re
from pathlib import Path


logger = logging.getLogger(__name__)


__all__ = [
    "get_plan_path",
    "plans_dir",
    "read_plan",
    "write_plan",
    "clear_plan",
]


# Mirrors the validator pattern used by SubagentTask.task_id.  We're
# strict on purpose: session ids are generated by uuid4() (hex,
# possibly with hyphens) and we don't want a path separator or dot
# segment to creep in via a misbehaving caller.
_SESSION_ID_RE = re.compile(r"^[A-Za-z0-9_-]+$")

# Prefix length used in the filename — short enough to be human-
# scannable in ``ls``, long enough to avoid collisions across the
# session ids users actually produce.
_PLAN_FILENAME_PREFIX = 8


def _aether_home() -> Path:
    """Return ``${AETHER_HOME}`` or the default ``~/.aether``.

    Mirrors :func:`aether.cli.prefs._aether_home`; kept as a local copy
    so this runtime module does not import the CLI layer.
    """
    raw = os.getenv("AETHER_HOME")
    if raw:
        return Path(raw)
    return Path.home() / ".aether"


def plans_dir() -> Path:
    """Return the directory holding all plan artifacts."""
    return _aether_home() / "plans"


def _validate_session_id(session_id: object) -> str:
    # Accept ``object`` rather than ``str`` so the function can also
    # defend against callers that bypass type-checking (e.g. wire
    # decoders that hand us a None or int).  Tests cover the non-str
    # case explicitly.
    if not isinstance(session_id, str):
        raise ValueError("session_id must be a string")
    cleaned = session_id.strip()
    if not cleaned:
        raise ValueError("session_id must not be empty")
    if not _SESSION_ID_RE.fullmatch(cleaned):
        raise ValueError(
            f"session_id contains unsafe characters: {session_id!r}"
        )
    return cleaned


def get_plan_path(session_id: str) -> Path:
    """Return the stable plan file path for ``session_id``.

    Filename is ``<session_id[:8]>.md``; same session id always maps
    to the same path (idempotent).  Does not create the file or its
    parent directory — callers should use :func:`write_plan` for that.
    """
    sid = _validate_session_id(session_id)
    return plans_dir() / f"{sid[:_PLAN_FILENAME_PREFIX]}.md"


def read_plan(session_id: str) -> str | None:
    """Return the plan contents or ``None`` when the artifact is absent.

    Never raises on a missing file; OS errors during read are logged
    and surfaced as ``None`` so callers (``plan.current`` RPC, TUI)
    can degrade gracefully instead of bubbling a stack trace into the
    user transcript.
    """
    try:
        path = get_plan_path(session_id)
    except ValueError:
        return None
    if not path.exists():
        return None
    try:
        return path.read_text(encoding="utf-8")
    except OSError as exc:
        logger.warning("plan artifact unreadable at %s: %s", path, exc)
        return None


def write_plan(session_id: str, content: str) -> Path:
    """Persist ``content`` as the plan for ``session_id``.

    Creates the parent directory if necessary.  Overwrites any existing
    plan so ``exit_plan_mode`` can iterate without leaving stale text.
    Returns the path written so the caller can show it to the user.
    """
    path = get_plan_path(session_id)
    path.parent.mkdir(parents=True, exist_ok=True)
    # Plain write_text — atomic enough for our purposes since the plan
    # file is only ever written by the tool (single writer) and a
    # partial write would be replaced on the next ``exit_plan_mode``.
    path.write_text(content, encoding="utf-8")
    return path


def clear_plan(session_id: str) -> None:
    """Remove the plan artifact if it exists.  Idempotent."""
    try:
        path = get_plan_path(session_id)
    except ValueError:
        return
    try:
        path.unlink(missing_ok=True)
    except OSError as exc:  # pragma: no cover - defensive
        logger.warning("plan artifact unlink failed at %s: %s", path, exc)
